server:
  port: ${PORT:8080}

spring:
  application:
    name: auth-system

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME:9a5a33001@smtp-brevo.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890}
      expiration: 86400000
      refresh-expiration: 604800000

    two-factor:
      issuer: "AuthSystem"

    verification:
      email:
        expiration: 86400000
      sms:
        expiration: 300000
        max-attempts: 3

    rate-limiting:
      max-login-attempts: 5
      lockout-duration: 900000

  base-url: ${FRONTEND_URL:http://localhost:4200}
  
  # Configuraciones de proveedores de email alternativos
  email:
    brevo:
      api-key: ${BREVO_API_KEY:#{null}}
    resend:
      api-key: ${RESEND_API_KEY:#{null}}
    sendgrid:
      api-key: ${SENDGRID_API_KEY:#{null}}
    mailgun:
      api-key: ${MAILGUN_API_KEY:#{null}}
      domain: ${MAILGUN_DOMAIN:#{null}}

  notification:
    sms:
      provider: sinch
      project-id: ${SINCH_PROJECT_ID:4696842a27654b618a9609091afdb8d9}
      access-key-id: ${SINCH_ACCESS_KEY_ID:ea55ba6d-0381-4df8-b66b-4afff2ffbeab}
      secret-key: ${SINCH_SECRET_KEY:39cb2c4b8b87402ba17fb4bbf0fbac45}
      from-number: ${SINCH_FROM_NUMBER:+447418630656}
      dev-mode: false

logging:
  level:
    com.security: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web.servlet: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.boot.autoconfigure.mail: DEBUG
